#ifndef BANK_H
#define BANK_H

#include "questionbank.h"

/* use html supported subsets to modify how questions are to be displayed by the Qlabel widget
 * mostly use the italics and the bold subsets of the html subsets
 * <b><i>Question string</i></b>
 */

class Jamb2008English:public QuestionBank
{
    //WAEC 2008, ENGLISH (not JAMB: FOR TESTING PURPOSES)
    void setupQuestions()
    {
        fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>SECTION 1:</b>\n<i>In each of the following sentences, there is one underlined word and one gap. From the list of words lettered <b>A</b> to <b>D</b>, choose the one that is most nearly opposite in meaning to the underlined word and that will, at the same time, correctly fill the gap in the sentence</i></font>","","","","","","",true)); //
        fQuestions->push_back(QuestionAnswer("<font size=6>Good teaching <u>stimulates</u> the interest of students, whereas bad teaching ......... it</font>","A. dampens","B. encourages","C. supersedes","D. retracts","","1/100")); //1
        fQuestions->push_back(QuestionAnswer("<font size=6>Some youths of this generation are often <u>hard-headed</u> compared to those of past generations who were .........</font>","A. indifferent","B. fastidious","C. proficient","D. compassionate","","2/100"));   //2
        fQuestions->push_back(QuestionAnswer("<font size=6>The doctor does not think the patient will recover; the signs are <u>ominous</u> rather than .........</font>","A. encouraging","B. feasible","C. obvious","D. gloomy","","3/100")); //3
        fQuestions->push_back(QuestionAnswer("<font size=6>The purpose of education is to <u>enhance</u> progress and not to ......... it.</font>","A. proscribe","B. intercept","C. impede","D. confuse","","4/100"));   //4
        fQuestions->push_back(QuestionAnswer("<font size=6>The teacher gave him high marks and wrote <u>complimentary</u> remarks in the margin, which surprisingly gave him .......... feelings.</font>","A. doubtful","B. secret","C. unpleasant","D. serious","","5/100")); //5
        fQuestions->push_back(QuestionAnswer("<font size=6>Many people find cod liver oil <u>disgusting</u> but soldiers find it .........</font>","A. refreshing","B. medicinal","C. pleasant","D. bitter","","6/100"));   //6
        fQuestions->push_back(QuestionAnswer("<font size=6>The investigators relied solely on <u>conjectures</u>, which were not as reliable as .........</font>","A. facts","B. hearsay","C. figures","D. fabrications","","7/100"));  //7
        fQuestions->push_back(QuestionAnswer("<font size=6>It was <u>obvious</u> that Modou committed the crime, but his friends were still .........</font>","A. unhappy","B. doubtful","C. suspicious","D. confident","","8/100"));   //8
        fQuestions->push_back(QuestionAnswer("<font size=6>The government was blamed for implementing policies that favoured the <u>elite</u> at the expense of the ..........</font>","A. workers","B. wealthy","C. masses","D. oppressed","","9/100"));    //9
        fQuestions->push_back(QuestionAnswer("<font size=6>His suggestion on how to deal with the thief was <u>invaluable</u>, but the police considered it .........</font>","A. useless","B. impossible","C. necessary","D. timely","","10/100"));   //10

        fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>SECTION 2:</b>\n<i>From the words lettered <b>A</b> to <b>D</b>, choose the word that best completes each of the following sentences.</font>","","","","","","",true));  //
        fQuestions->push_back(QuestionAnswer("<font size=6>The woman's behaviour clearly shows that her love for her husband was merely .........</font>","A. superstitious","B. superlative","C. elusive","D. superficial","","11/100"));  //11
        fQuestions->push_back(QuestionAnswer("<font size=6>The man was told in his own interest to ......... the statement he had made.</font>","A. cancel","B. recast","C. erase","D. retract","","12/100"));  //12
        fQuestions->push_back(QuestionAnswer("<font size=6>Mum made soothing remarks in order to ......... dad.</font>","A. incense","B. pacify","C. rekindle","D. protect","","13/100"));  //13
        fQuestions->push_back(QuestionAnswer("<font size=6>Ebou maintained his stand in ......... of the principals orders.</font>","A. defiance","B. deference","C. obedience","D. defence","","14/100"));   //14
        fQuestions->push_back(QuestionAnswer("<font size=6>The outgoing president warned his successor to beware of ......... who praises every action of government, good or bad</font>","A. enthusiasts","B. sycophants","C. radicals","D. favourites","","15/100"));  //15
        fQuestions->push_back(QuestionAnswer("<font size=6>Salimate came into ......... when she won the beauty contest</font>","A. public","B. limelight","C. focus","D. view","","16/100"));  //16
        fQuestions->push_back(QuestionAnswer("<font size=6>The current economic crisis had led to the ......... of many workers</font>","A. rejection","B. retrenchment","C. isolation","D. ejection","","17/100"));   //17
        fQuestions->push_back(QuestionAnswer("<font size=6>We all agree that the television is a more powerful ......... of communication than the radio</font>","A. agent","B. way","C. instrument","D. medium","","18/100")); //18
        fQuestions->push_back(QuestionAnswer("<font size=6>He won the election by a ......... of 500 votes.</font>","A. consensus","B. margin","C. surplus","D. gap","","19/100")); //19
        fQuestions->push_back(QuestionAnswer("<font size=6>Daylight armed-robbery is a common ......... in big cities</font>","A. plan","B. site","C. exercise","D. phenomenon","","20/100"));   //20

        fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>SECTION 3:</b>\n<i>After each of the following sentences, a list possible interpretations is given. Choose the interpretation that you consider <b>most appropriate</b> for each sentence.</font>","","","","","","",true));
        fQuestions->push_back(QuestionAnswer("<font size=6>When Joe was threatened with suspension he made a clean breast of his offence. This means that Joe</font>","A. ran away","B. made friends with the other offenders","C. told the whole truth","D. pleaded innocence","","21/100"));  //21
        fQuestions->push_back(QuestionAnswer("<font size=6>When Eunice was discharged from hospital she was a shadow of her former self. This means that she</font>","A. looked like a shadow","B. was withdrawn","C. had changed a little","D. was thin and weak","","22/100"));  //22
        fQuestions->push_back(QuestionAnswer("<font size=6>Chinwe can be stubborn yet i have a soft spot for her. This means that I</font>","A. am fond of chinwe even though she is stubborn ","B. alone know how to control chinwe","C. dislike chinwe for stubbornness","D. have a cure for her stubbornness","","23/100"));   //23
        fQuestions->push_back(QuestionAnswer("<font size=6>The principal is high-handed with his staff. This means that the principal</font>","A. respects his staff highly","B. is very friendly and easy going with his staff","C. shakes hand with his staff frequently","D. uses his authority over his staff very sternly","","24/100"));	//24
        fQuestions->push_back(QuestionAnswer("<font size=6>The loan was taken on a gentleman's agreement. This means that </font>","A. there was no documentation of the loan","B. two gentlemen witnessed the loan","C. the loan was granted","D. the loan was not to be repaid","","25/100"));	//25
        fQuestions->push_back(QuestionAnswer("<font size=6>Constructing the road along the coast was difficult but the men had already broken the back of the work before the rains. This means that they had </font>","A. completed the preparations","B. completed the most difficult part of it","C. completed it altogether","D. broken the road","","26/100"));	//26
        fQuestions->push_back(QuestionAnswer("<font size=6>Whenever Nkoyo finds herself at a loose end, she goes visiting people. This means that Nkoyo goes visiting people  whenever she</font>","A. is happy","B. feels worried and confused","C. has nothing to occupy her","D. has no visitors","","27/100"));	//27
        fQuestions->push_back(QuestionAnswer("<font size=6>Kola will get the job because his father will surely pull strings for him. This means that his father will</font>","A. give him useful information","B. remove some of his difficulties","C. influence the right people","D. attract attention towards him","","28/100"));	//28
        fQuestions->push_back(QuestionAnswer("<font size=6>To give a bronze medal to the athlete who was deliberately intercepted on the track was cold comfort. This means that the bronze medal was</font>","A. acceptable to him","B. too cold","C. not adequate compensation","D. rejected by him","","29/100"));	//29
		fQuestions->push_back(QuestionAnswer("<font size=6>The students planned to confront the principal with their grievances but as they got closer to his office, they developed cold feet. This means that</font>","A. they could no longer walk","B. they lost courage","C. they lost interest","D. their feet became numb","","30/100"));	//30
		
        fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>SECTION 4:</b>\n<i>From the words lettered <b>A</b> to <b>D</b> below each of the following sentences, choose the word or group of words that is <b>nearest in meaning</b> to the underlined word as it is used in the sentence</i></font>","","","","","","",true));	//
        fQuestions->push_back(QuestionAnswer("<font size=6>The woman <u>stifled</u> a cry of astonishment as she discovered the identity of the robber</font>","A. suppressed","B. shouted","C. forced","D. hid","","31/100"));	//31
		fQuestions->push_back(QuestionAnswer("<font size=6>That rock is <u>a potential</u> danger to fishing boats</font>","A. a possible","B. an unexpected","C. an obvious","D. a serious","","32/100"));	//32
        fQuestions->push_back(QuestionAnswer("<font size=6>His contribution to the development programme in the village remains <u>unrivalled</u></font>","A. unbroken","B. unparalleled","C. undisputed","D. unknown","","33/100"));	//33
        fQuestions->push_back(QuestionAnswer("<font size=6>Members of the party agreed that some serious <u>thinking</u> is required before a final decision can be taken</font>","A. meetings","B. consultation","C. consideration","D. appraisal","","34/100"));	//34
		fQuestions->push_back(QuestionAnswer("<font size=6>Our chief is very intelligent but he could he could be <u>parochial</u> in his judgements</font>","A. deep","B. broad","C. narrow-minded","D. kind-hearted","","35/100"));	//35
        fQuestions->push_back(QuestionAnswer("<font size=6>All that was left after the riot were the <u>charred</u> remains of the victims</font>","A. burnt","B. black","C. broken","D. scattered","","36/100"));	//36
        fQuestions->push_back(QuestionAnswer("<font size=6>The <u>incessant</u> chatter of the pupils irritated the visitor</font>","A. unceasing","B. meaningless","C. excited","D. loud","","37/100"));	//37
		fQuestions->push_back(QuestionAnswer("<font size=6>Musa won the debate because he <u>articulated</u> his arguments convincingly</font>","A. pronounced","B. presented","C. arranged","D. summarized","","38/100"));	//38
        fQuestions->push_back(QuestionAnswer("<font size=6>I was surprised at the <u>gallantry</u> of the Senegalese peace-keepers</font>","A. cowardice","B. strength","C. bravery","D. height","","39/100"));	//39
        fQuestions->push_back(QuestionAnswer("<font size=6>The clerk was dismissed for <u>dereliction</u> of duty</font>","A. ignorance","B. lateness","C. carelessness","D. negligence","","40/100"));	//40
		
		fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>SECTION 5</b>\n<i>From the word or group of words lettered <b>A</b> to <b>D</b>, choose the word or group of words that <b>best completes</b> each of the following sentences</i></font>","","","","","","",true));	//
        fQuestions->push_back(QuestionAnswer("<font size=6>This is a bad case, ......... hard you try to defend the accused</font>","A. however","B. whatever","C. whichever","D. whenever","","41/100"));	//41
        fQuestions->push_back(QuestionAnswer("<font size=6>......... pain has been taken to make the party a success</font>","A. Such","B. Much","C. Every","D. Many","","42/100"));	//42
		fQuestions->push_back(QuestionAnswer("<font size=6>School children are advised to refrain ......... smoking</font>","A. with","B. against","C. to","D. from","","43/100"));	//43
        fQuestions->push_back(QuestionAnswer("<font size=6>The principal, as well as the teachers, ......... in school</font>","A. is","B. were","C. all are","D. are all","","44/100"));	//44
        fQuestions->push_back(QuestionAnswer("<font size=6>Fatima ......... come to work today since she is still sick</font>","A. needn't had","B. needn't have","C. needn't has","D. needn't to","","45/100"));	//45
		fQuestions->push_back(QuestionAnswer("<font size=6>Animata has ......... her engagement to sule.</font>","A. broken off","B. broken up","C. broken away","D. broken down","","46/100"));	//46
        fQuestions->push_back(QuestionAnswer("<font size=6>......... who knows the times will not open his door to strangers at night</font>","A. Somebody","B. Nobody","C. Anybody","D. Everybody","","47/100"));	//47
        fQuestions->push_back(QuestionAnswer("<font size=6>All the final year students will attend ......... party</font>","A. tomorrow's","B. tomorrows'","C. tomorrows","D. tomorrow","","48/100"));	//48
		fQuestions->push_back(QuestionAnswer("<font size=6>My friend's son stole the ......... briefcase</font>","A. director's-general","B. director-general's","C. directors'-general","D. director-generals'","","49/100"));	//49
        fQuestions->push_back(QuestionAnswer("<font size=6>This isn't your ring; it is your .........</font>","A. daughter-in-law","B. daughter-in-law's","C. daughters-in-law","D. daughter-in-laws","","50/100"));	//50
        fQuestions->push_back(QuestionAnswer("<font size=6>He brought us .........</font>","A. a good news","B. many good news","C. some good news","D. several good news","","51/100"));	//51
		fQuestions->push_back(QuestionAnswer("<font size=6>I was asked whether i ......... to go on the outing</font>","A. would intend","B. intended","C. have intended","D. intend","","52/100"));	//52
        fQuestions->push_back(QuestionAnswer("<font size=6>Our teacher is leaving our school in July to ......... a new job</font>","A. take in","B. take to","C. take on","D. take up","","53/100"));	//53
        fQuestions->push_back(QuestionAnswer("<font size=6>The old woman had no children and no real friends .........</font>","A. too","B. again","C. either","D. neither","","54/100"));	//54
		fQuestions->push_back(QuestionAnswer("<font size=6>Certain tasks may be unpleasant first, but gradually one may get ......... them</font>","A. to liking","B. to like","C. to be liking","D. to have liked","","55/100"));	//55
        fQuestions->push_back(QuestionAnswer("<font size=6>......... in their youth is a source of pleasurable reminiscence for elderly persons</font>","A. To be travelling","B. To travel","C. By travelling","D. To have travelled","","56/100"));	//56
        fQuestions->push_back(QuestionAnswer("<font size=6>The minister told his congregation that one day ......... would be rewarded</font>","A. the faithfuls","B. the faithful","C. any faithfuls","D. a faithful","","57/100"));	//57
		fQuestions->push_back(QuestionAnswer("<font size=6>Maram liked the exhibits at the trade fair but she really enjoyed ......... the most</font>","A. the amusements","B. amusements","C. the amusement","D. amusement","","58/100"));	//58
        fQuestions->push_back(QuestionAnswer("<font size=6>The jury gave ......... verdict of guilty in the murder case</font>","A. it's","B. 'tis","C. it","D. its","","59/100"));	//59
        fQuestions->push_back(QuestionAnswer("<font size=6>The room in ......... they lived was quite large and well-lit</font>","A. where","B. that","C. which","D. there","","60/100"));	//60
		fQuestions->push_back(QuestionAnswer("<font size=6>The great gates of the ancient palace were ......... </font>","A. beautiful pieces of iron works","B. the beautiful pieces of iron works","C. beautiful pieces of iron work","D. the beautiful piece of iron works","","61/100"));	//61
        fQuestions->push_back(QuestionAnswer("<font size=6>The report said that although the country was rich ......... formed a substantial part of the population</font>","A. old and neglected","B. the old and neglected","C. some old and some neglected","D. the olds and neglected","","62/100"));	//62
        fQuestions->push_back(QuestionAnswer("<font size=6>I had a phone call from her yesterday, so she ......... have found out my telephone number</font>","A. can","B. could","C. must","D. might","","63/100"));	//63
		fQuestions->push_back(QuestionAnswer("<font size=6>I cannot imagine that a man ......... his standing could stoop so low as to accept bribes</font>","A. with","B. at","C. of","D. on","","64/100"));	//64
        fQuestions->push_back(QuestionAnswer("<font size=6>Lamin and Michael washed ......... but mummy washed yeanie</font>","A. himself","B. themselves","C. one another","D. the other","","65/100"));	//65
        fQuestions->push_back(QuestionAnswer("<font size=6>The principal has gone to Freetown and will come back in ......... time</font>","A. two weeks","B. two week","C. two week's","D. two weeks'","","66/100"));	//66
		fQuestions->push_back(QuestionAnswer("<font size=6>The students have not come back from their school farms .........</font>","A. isn't it","B. hadn't they","C. didn't they","D. have they","","67/100"));	//67
        fQuestions->push_back(QuestionAnswer("<font size=6>We haven't confirmed ......... signature this is</font>","A. what","B. whose","C. who's","D. which","","68/100"));	//68
        fQuestions->push_back(QuestionAnswer("<font size=6>I said \"John saw Mary\", .........?</font>","A. didn't I","B. didn't he","C. hadn't he","D. do I","","69/100"));	//69
		fQuestions->push_back(QuestionAnswer("<font size=6>The moon seemed to be sailing through the clouds ......... a ship thrusting its way through a stormy ocean</font>","A. as","B. as to","C. as for","D. like","","70/100"));	//70
        fQuestions->push_back(QuestionAnswer("<font size=6>The school's high jump champion has been .........</font>","A. off very much form most of the time","B. very much off-form most of the time","C. very most off-form most of the time","D. off-form most of the time very much","","71/100"));	//71
        fQuestions->push_back(QuestionAnswer("<font size=6>The new bridge was a complete waste of money and ......... built in the first place</font>","A. need not have been","B. needs not have been","C. needed not to have been","D. need not to have been","","72/100"));	//72
		fQuestions->push_back(QuestionAnswer("<font size=6>Araba took up an appointment as a part-time instructor as a means ......... his meagre income</font>","A. to supplement","B. of supplementing","C. to supplementing","D. for supplementing","","73/100"));	//73
        fQuestions->push_back(QuestionAnswer("<font size=6>......... opportunity we now have to rid the nation of corruption!</font>","A. What excellent","B. What an excellent","C. How excellent","D. So excellent an","","74/100"));	//74
		
        fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>SECTION 6</b>\n<i>In the following passages, the numbered gaps indicate missing words. Against each number in the list below each passage, <b>options</b> are given lettered <b>A</b> to <b>D</b>. Choose the word that is the <b>most suitable</b> to fill the numbered gaps in the passages.</i></font>","","","","","","",true));	//
		fQuestions->push_back(QuestionAnswer("<font size=6></font>","","","","","","75/100"));	//75
        fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>PASSAGE A</b>\n\tOne of the indicators of __<b>76</b>__ underdevelopment in this country is the backward state of the transport sector. This is typified by the poor state of the railway __<b>77</b>__. In advanced countries, commuter trains carry passengers from city to city and within suburbs. The __<b>78</b>__ train goes a lot faster connecting major cities and even states; such trains have __<b>79</b>__ only.\n\tIn the intra-city trains, it is only shelter and seats that are provided. There are no __<b>80</b>__. In some cases, and because of the long hours of service of inter-city or inter-state trains, __<b>81</b>__ and __<b>82</b>__ are available in addition to coaches.\n\tApart from the very fast electric trains, there are passenger trains that are __<b>83</b>__ powered. There are others that use coal or steam as __<b>84</b>__. Some trains offer __<b>85</b>__ services, transporting goods. Such trains stop at specific __<b>86</b>__ to deliver goods or to refuel. Most trains have __<b>87</b>__ to push or pull them to prevent them from turning around.</font>","A. Structural","B. infrastructural","C. fiscal","D. systematic","","76/100"));	//76
        fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>PASSAGE A</b>\n\tOne of the indicators of __<b>76</b>__ underdevelopment in this country is the backward state of the transport sector. This is typified by the poor state of the railway __<b>77</b>__. In advanced countries, commuter trains carry passengers from city to city and within suburbs. The __<b>78</b>__ train goes a lot faster connecting major cities and even states; such trains have __<b>79</b>__ only.\n\tIn the intra-city trains, it is only shelter and seats that are provided. There are no __<b>80</b>__. In some cases, and because of the long hours of service of inter-city or inter-state trains, __<b>81</b>__ and __<b>82</b>__ are available in addition to coaches.\n\tApart from the very fast electric trains, there are passenger trains that are __<b>83</b>__ powered. There are others that use coal or steam as __<b>84</b>__. Some trains offer __<b>85</b>__ services, transporting goods. Such trains stop at specific __<b>86</b>__ to deliver goods or to refuel. Most trains have __<b>87</b>__ to push or pull them to prevent them from turning around.</font>","A. system","B. framework","C. industry","D. business","","77/100"));	//77
		fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>PASSAGE A</b>\n\tOne of the indicators of __<b>76</b>__ underdevelopment in this country is the backward state of the transport sector. This is typified by the poor state of the railway __<b>77</b>__. In advanced countries, commuter trains carry passengers from city to city and within suburbs. The __<b>78</b>__ train goes a lot faster connecting major cities and even states; such trains have __<b>79</b>__ only.\n\tIn the intra-city trains, it is only shelter and seats that are provided. There are no __<b>80</b>__. In some cases, and because of the long hours of service of inter-city or inter-state trains, __<b>81</b>__ and __<b>82</b>__ are available in addition to coaches.\n\tApart from the very fast electric trains, there are passenger trains that are __<b>83</b>__ powered. There are others that use coal or steam as __<b>84</b>__. Some trains offer __<b>85</b>__ services, transporting goods. Such trains stop at specific __<b>86</b>__ to deliver goods or to refuel. Most trains have __<b>87</b>__ to push or pull them to prevent them from turning around.</font>","A. intra-city","B. in-city","C. inter-city","D. sub-city","","78/100"));	//78
        fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>PASSAGE A</b>\n\tOne of the indicators of __<b>76</b>__ underdevelopment in this country is the backward state of the transport sector. This is typified by the poor state of the railway __<b>77</b>__. In advanced countries, commuter trains carry passengers from city to city and within suburbs. The __<b>78</b>__ train goes a lot faster connecting major cities and even states; such trains have __<b>79</b>__ only.\n\tIn the intra-city trains, it is only shelter and seats that are provided. There are no __<b>80</b>__. In some cases, and because of the long hours of service of inter-city or inter-state trains, __<b>81</b>__ and __<b>82</b>__ are available in addition to coaches.\n\tApart from the very fast electric trains, there are passenger trains that are __<b>83</b>__ powered. There are others that use coal or steam as __<b>84</b>__. Some trains offer __<b>85</b>__ services, transporting goods. Such trains stop at specific __<b>86</b>__ to deliver goods or to refuel. Most trains have __<b>87</b>__ to push or pull them to prevent them from turning around.</font>","A. wagons","B. coaches","C. cabins","D. decks","","79/100"));	//79
        fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>PASSAGE A</b>\n\tOne of the indicators of __<b>76</b>__ underdevelopment in this country is the backward state of the transport sector. This is typified by the poor state of the railway __<b>77</b>__. In advanced countries, commuter trains carry passengers from city to city and within suburbs. The __<b>78</b>__ train goes a lot faster connecting major cities and even states; such trains have __<b>79</b>__ only.\n\tIn the intra-city trains, it is only shelter and seats that are provided. There are no __<b>80</b>__. In some cases, and because of the long hours of service of inter-city or inter-state trains, __<b>81</b>__ and __<b>82</b>__ are available in addition to coaches.\n\tApart from the very fast electric trains, there are passenger trains that are __<b>83</b>__ powered. There are others that use coal or steam as __<b>84</b>__. Some trains offer __<b>85</b>__ services, transporting goods. Such trains stop at specific __<b>86</b>__ to deliver goods or to refuel. Most trains have __<b>87</b>__ to push or pull them to prevent them from turning around.</font>","A. bookshops and libraries","B. gyms and clubs","C. meals and refreshments","D. parks and salons","","80/100"));	//80
		fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>PASSAGE A</b>\n\tOne of the indicators of __<b>76</b>__ underdevelopment in this country is the backward state of the transport sector. This is typified by the poor state of the railway __<b>77</b>__. In advanced countries, commuter trains carry passengers from city to city and within suburbs. The __<b>78</b>__ train goes a lot faster connecting major cities and even states; such trains have __<b>79</b>__ only.\n\tIn the intra-city trains, it is only shelter and seats that are provided. There are no __<b>80</b>__. In some cases, and because of the long hours of service of inter-city or inter-state trains, __<b>81</b>__ and __<b>82</b>__ are available in addition to coaches.\n\tApart from the very fast electric trains, there are passenger trains that are __<b>83</b>__ powered. There are others that use coal or steam as __<b>84</b>__. Some trains offer __<b>85</b>__ services, transporting goods. Such trains stop at specific __<b>86</b>__ to deliver goods or to refuel. Most trains have __<b>87</b>__ to push or pull them to prevent them from turning around.</font>","A. dining cars","B. lunch tables","C. refectories","D. bars","","81/100"));	//81
        fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>PASSAGE A</b>\n\tOne of the indicators of __<b>76</b>__ underdevelopment in this country is the backward state of the transport sector. This is typified by the poor state of the railway __<b>77</b>__. In advanced countries, commuter trains carry passengers from city to city and within suburbs. The __<b>78</b>__ train goes a lot faster connecting major cities and even states; such trains have __<b>79</b>__ only.\n\tIn the intra-city trains, it is only shelter and seats that are provided. There are no __<b>80</b>__. In some cases, and because of the long hours of service of inter-city or inter-state trains, __<b>81</b>__ and __<b>82</b>__ are available in addition to coaches.\n\tApart from the very fast electric trains, there are passenger trains that are __<b>83</b>__ powered. There are others that use coal or steam as __<b>84</b>__. Some trains offer __<b>85</b>__ services, transporting goods. Such trains stop at specific __<b>86</b>__ to deliver goods or to refuel. Most trains have __<b>87</b>__ to push or pull them to prevent them from turning around.</font>","A. closets","B. sleeping cars","C. cloakrooms","D. control suites","","82/100"));	//82
        fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>PASSAGE A</b>\n\tOne of the indicators of __<b>76</b>__ underdevelopment in this country is the backward state of the transport sector. This is typified by the poor state of the railway __<b>77</b>__. In advanced countries, commuter trains carry passengers from city to city and within suburbs. The __<b>78</b>__ train goes a lot faster connecting major cities and even states; such trains have __<b>79</b>__ only.\n\tIn the intra-city trains, it is only shelter and seats that are provided. There are no __<b>80</b>__. In some cases, and because of the long hours of service of inter-city or inter-state trains, __<b>81</b>__ and __<b>82</b>__ are available in addition to coaches.\n\tApart from the very fast electric trains, there are passenger trains that are __<b>83</b>__ powered. There are others that use coal or steam as __<b>84</b>__. Some trains offer __<b>85</b>__ services, transporting goods. Such trains stop at specific __<b>86</b>__ to deliver goods or to refuel. Most trains have __<b>87</b>__ to push or pull them to prevent them from turning around.</font>","A. battery-","B. engine-","C. diesel-","D. solar-","","83/100"));	//83
		fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>PASSAGE A</b>\n\tOne of the indicators of __<b>76</b>__ underdevelopment in this country is the backward state of the transport sector. This is typified by the poor state of the railway __<b>77</b>__. In advanced countries, commuter trains carry passengers from city to city and within suburbs. The __<b>78</b>__ train goes a lot faster connecting major cities and even states; such trains have __<b>79</b>__ only.\n\tIn the intra-city trains, it is only shelter and seats that are provided. There are no __<b>80</b>__. In some cases, and because of the long hours of service of inter-city or inter-state trains, __<b>81</b>__ and __<b>82</b>__ are available in addition to coaches.\n\tApart from the very fast electric trains, there are passenger trains that are __<b>83</b>__ powered. There are others that use coal or steam as __<b>84</b>__. Some trains offer __<b>85</b>__ services, transporting goods. Such trains stop at specific __<b>86</b>__ to deliver goods or to refuel. Most trains have __<b>87</b>__ to push or pull them to prevent them from turning around.</font>","A. petrol","B. alternative","C. converter","D. fuel","","84/100"));	//84
        fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>PASSAGE A</b>\n\tOne of the indicators of __<b>76</b>__ underdevelopment in this country is the backward state of the transport sector. This is typified by the poor state of the railway __<b>77</b>__. In advanced countries, commuter trains carry passengers from city to city and within suburbs. The __<b>78</b>__ train goes a lot faster connecting major cities and even states; such trains have __<b>79</b>__ only.\n\tIn the intra-city trains, it is only shelter and seats that are provided. There are no __<b>80</b>__. In some cases, and because of the long hours of service of inter-city or inter-state trains, __<b>81</b>__ and __<b>82</b>__ are available in addition to coaches.\n\tApart from the very fast electric trains, there are passenger trains that are __<b>83</b>__ powered. There are others that use coal or steam as __<b>84</b>__. Some trains offer __<b>85</b>__ services, transporting goods. Such trains stop at specific __<b>86</b>__ to deliver goods or to refuel. Most trains have __<b>87</b>__ to push or pull them to prevent them from turning around.</font>","A. freight","B. delivery","C. postal","D. courier","","85/100"));	//85
        fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>PASSAGE A</b>\n\tOne of the indicators of __<b>76</b>__ underdevelopment in this country is the backward state of the transport sector. This is typified by the poor state of the railway __<b>77</b>__. In advanced countries, commuter trains carry passengers from city to city and within suburbs. The __<b>78</b>__ train goes a lot faster connecting major cities and even states; such trains have __<b>79</b>__ only.\n\tIn the intra-city trains, it is only shelter and seats that are provided. There are no __<b>80</b>__. In some cases, and because of the long hours of service of inter-city or inter-state trains, __<b>81</b>__ and __<b>82</b>__ are available in addition to coaches.\n\tApart from the very fast electric trains, there are passenger trains that are __<b>83</b>__ powered. There are others that use coal or steam as __<b>84</b>__. Some trains offer __<b>85</b>__ services, transporting goods. Such trains stop at specific __<b>86</b>__ to deliver goods or to refuel. Most trains have __<b>87</b>__ to push or pull them to prevent them from turning around.</font>","A. checkpoints","B. duty-posts","C. stations","D. centres","","86/100"));	//86
		fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>PASSAGE A</b>\n\tOne of the indicators of __<b>76</b>__ underdevelopment in this country is the backward state of the transport sector. This is typified by the poor state of the railway __<b>77</b>__. In advanced countries, commuter trains carry passengers from city to city and within suburbs. The __<b>78</b>__ train goes a lot faster connecting major cities and even states; such trains have __<b>79</b>__ only.\n\tIn the intra-city trains, it is only shelter and seats that are provided. There are no __<b>80</b>__. In some cases, and because of the long hours of service of inter-city or inter-state trains, __<b>81</b>__ and __<b>82</b>__ are available in addition to coaches.\n\tApart from the very fast electric trains, there are passenger trains that are __<b>83</b>__ powered. There are others that use coal or steam as __<b>84</b>__. Some trains offer __<b>85</b>__ services, transporting goods. Such trains stop at specific __<b>86</b>__ to deliver goods or to refuel. Most trains have __<b>87</b>__ to push or pull them to prevent them from turning around.</font>","A. gadgets","B. locomotives","C. compasses","D. bearings","","87/100"));	//87
		
        fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>PASSAGE B</b>\n\tIt is interesting to watch a modern __<b>88</b>__ spring up and get completed in a matter of months. A few months ago, a building company brought some __<b>89</b>__ to the virgin forest next to our school. The trees were __<b>90</b>__, the ground was cleared and __<b>91</b>__, and the workers brought out various __<b>92</b>__ with which they measured and marked the __<b>93</b>__. Then the _<b>94</b>__ was dug and the __<b>95</b>__ were brought from somewhere else. __<b>96</b>__ was made from a mixture of sand, cement and water, and the walls grew before our very eyes. Before the end of the second month, we realized ot was not going to be a __<b>97</b>__ but a storeyed building. The __<b>98</b>__ was cast in only one day by the workers who __<b>99</b>__ for the whole day. Thereafter, things moved even faster. By the end of the month, the whole __<b>100</b>__ was in place.</font>","A. construction","B. building","C. erection","D. fabrication","","88/100"));	//88
        fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>PASSAGE B</b>\n\tIt is interesting to watch a modern __<b>88</b>__ spring up and get completed in a matter of months. A few months ago, a building company brought some __<b>89</b>__ to the virgin forest next to our school. The trees were __<b>90</b>__, the ground was cleared and __<b>91</b>__, and the workers brought out various __<b>92</b>__ with which they measured and marked the __<b>93</b>__. Then the _<b>94</b>__ was dug and the __<b>95</b>__ were brought from somewhere else. __<b>96</b>__ was made from a mixture of sand, cement and water, and the walls grew before our very eyes. Before the end of the second month, we realized ot was not going to be a __<b>97</b>__ but a storeyed building. The __<b>98</b>__ was cast in only one day by the workers who __<b>99</b>__ for the whole day. Thereafter, things moved even faster. By the end of the month, the whole __<b>100</b>__ was in place.</font>","A. trailers","B. bull-dozers","C. tractors","D. machines","","89/100"));	//89
		fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>PASSAGE B</b>\n\tIt is interesting to watch a modern __<b>88</b>__ spring up and get completed in a matter of months. A few months ago, a building company brought some __<b>89</b>__ to the virgin forest next to our school. The trees were __<b>90</b>__, the ground was cleared and __<b>91</b>__, and the workers brought out various __<b>92</b>__ with which they measured and marked the __<b>93</b>__. Then the _<b>94</b>__ was dug and the __<b>95</b>__ were brought from somewhere else. __<b>96</b>__ was made from a mixture of sand, cement and water, and the walls grew before our very eyes. Before the end of the second month, we realized ot was not going to be a __<b>97</b>__ but a storeyed building. The __<b>98</b>__ was cast in only one day by the workers who __<b>99</b>__ for the whole day. Thereafter, things moved even faster. By the end of the month, the whole __<b>100</b>__ was in place.</font>","A. felled","B. pulled","C. cut","D. broken","","90/100"));	//90
        fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>PASSAGE B</b>\n\tIt is interesting to watch a modern __<b>88</b>__ spring up and get completed in a matter of months. A few months ago, a building company brought some __<b>89</b>__ to the virgin forest next to our school. The trees were __<b>90</b>__, the ground was cleared and __<b>91</b>__, and the workers brought out various __<b>92</b>__ with which they measured and marked the __<b>93</b>__. Then the _<b>94</b>__ was dug and the __<b>95</b>__ were brought from somewhere else. __<b>96</b>__ was made from a mixture of sand, cement and water, and the walls grew before our very eyes. Before the end of the second month, we realized ot was not going to be a __<b>97</b>__ but a storeyed building. The __<b>98</b>__ was cast in only one day by the workers who __<b>99</b>__ for the whole day. Thereafter, things moved even faster. By the end of the month, the whole __<b>100</b>__ was in place.</font>","A. levelled","B. paved","C. demolished","D. destroyed","","91/100"));	//91
        fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>PASSAGE B</b>\n\tIt is interesting to watch a modern __<b>88</b>__ spring up and get completed in a matter of months. A few months ago, a building company brought some __<b>89</b>__ to the virgin forest next to our school. The trees were __<b>90</b>__, the ground was cleared and __<b>91</b>__, and the workers brought out various __<b>92</b>__ with which they measured and marked the __<b>93</b>__. Then the _<b>94</b>__ was dug and the __<b>95</b>__ were brought from somewhere else. __<b>96</b>__ was made from a mixture of sand, cement and water, and the walls grew before our very eyes. Before the end of the second month, we realized ot was not going to be a __<b>97</b>__ but a storeyed building. The __<b>98</b>__ was cast in only one day by the workers who __<b>99</b>__ for the whole day. Thereafter, things moved even faster. By the end of the month, the whole __<b>100</b>__ was in place.</font>","A. apparatus","B. items","C. machinery","D. equipment","","92/100"));	//92
		fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>PASSAGE B</b>\n\tIt is interesting to watch a modern __<b>88</b>__ spring up and get completed in a matter of months. A few months ago, a building company brought some __<b>89</b>__ to the virgin forest next to our school. The trees were __<b>90</b>__, the ground was cleared and __<b>91</b>__, and the workers brought out various __<b>92</b>__ with which they measured and marked the __<b>93</b>__. Then the _<b>94</b>__ was dug and the __<b>95</b>__ were brought from somewhere else. __<b>96</b>__ was made from a mixture of sand, cement and water, and the walls grew before our very eyes. Before the end of the second month, we realized ot was not going to be a __<b>97</b>__ but a storeyed building. The __<b>98</b>__ was cast in only one day by the workers who __<b>99</b>__ for the whole day. Thereafter, things moved even faster. By the end of the month, the whole __<b>100</b>__ was in place.</font>","A. plan","B. trenches","C. ground","D. space","","93/100"));	//93
        fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>PASSAGE B</b>\n\tIt is interesting to watch a modern __<b>88</b>__ spring up and get completed in a matter of months. A few months ago, a building company brought some __<b>89</b>__ to the virgin forest next to our school. The trees were __<b>90</b>__, the ground was cleared and __<b>91</b>__, and the workers brought out various __<b>92</b>__ with which they measured and marked the __<b>93</b>__. Then the _<b>94</b>__ was dug and the __<b>95</b>__ were brought from somewhere else. __<b>96</b>__ was made from a mixture of sand, cement and water, and the walls grew before our very eyes. Before the end of the second month, we realized ot was not going to be a __<b>97</b>__ but a storeyed building. The __<b>98</b>__ was cast in only one day by the workers who __<b>99</b>__ for the whole day. Thereafter, things moved even faster. By the end of the month, the whole __<b>100</b>__ was in place.</font>","A. base","B. foundation","C. pavement","D. gutter","","94/100"));	//94
        fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>PASSAGE B</b>\n\tIt is interesting to watch a modern __<b>88</b>__ spring up and get completed in a matter of months. A few months ago, a building company brought some __<b>89</b>__ to the virgin forest next to our school. The trees were __<b>90</b>__, the ground was cleared and __<b>91</b>__, and the workers brought out various __<b>92</b>__ with which they measured and marked the __<b>93</b>__. Then the _<b>94</b>__ was dug and the __<b>95</b>__ were brought from somewhere else. __<b>96</b>__ was made from a mixture of sand, cement and water, and the walls grew before our very eyes. Before the end of the second month, we realized ot was not going to be a __<b>97</b>__ but a storeyed building. The __<b>98</b>__ was cast in only one day by the workers who __<b>99</b>__ for the whole day. Thereafter, things moved even faster. By the end of the month, the whole __<b>100</b>__ was in place.</font>","A. boreholes","B. lintels","C. fences","D. blocks","","95/100"));	//95
		fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>PASSAGE B</b>\n\tIt is interesting to watch a modern __<b>88</b>__ spring up and get completed in a matter of months. A few months ago, a building company brought some __<b>89</b>__ to the virgin forest next to our school. The trees were __<b>90</b>__, the ground was cleared and __<b>91</b>__, and the workers brought out various __<b>92</b>__ with which they measured and marked the __<b>93</b>__. Then the _<b>94</b>__ was dug and the __<b>95</b>__ were brought from somewhere else. __<b>96</b>__ was made from a mixture of sand, cement and water, and the walls grew before our very eyes. Before the end of the second month, we realized ot was not going to be a __<b>97</b>__ but a storeyed building. The __<b>98</b>__ was cast in only one day by the workers who __<b>99</b>__ for the whole day. Thereafter, things moved even faster. By the end of the month, the whole __<b>100</b>__ was in place.</font>","A. Concoction","B. Gravel","C. Mortar","D. Compound","","96/100"));	//96
        fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>PASSAGE B</b>\n\tIt is interesting to watch a modern __<b>88</b>__ spring up and get completed in a matter of months. A few months ago, a building company brought some __<b>89</b>__ to the virgin forest next to our school. The trees were __<b>90</b>__, the ground was cleared and __<b>91</b>__, and the workers brought out various __<b>92</b>__ with which they measured and marked the __<b>93</b>__. Then the _<b>94</b>__ was dug and the __<b>95</b>__ were brought from somewhere else. __<b>96</b>__ was made from a mixture of sand, cement and water, and the walls grew before our very eyes. Before the end of the second month, we realized ot was not going to be a __<b>97</b>__ but a storeyed building. The __<b>98</b>__ was cast in only one day by the workers who __<b>99</b>__ for the whole day. Thereafter, things moved even faster. By the end of the month, the whole __<b>100</b>__ was in place.</font>","A. basement","B. mansion","C. bungalow","D. sky-scraper","","97/100"));	//97
        fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>PASSAGE B</b>\n\tIt is interesting to watch a modern __<b>88</b>__ spring up and get completed in a matter of months. A few months ago, a building company brought some __<b>89</b>__ to the virgin forest next to our school. The trees were __<b>90</b>__, the ground was cleared and __<b>91</b>__, and the workers brought out various __<b>92</b>__ with which they measured and marked the __<b>93</b>__. Then the _<b>94</b>__ was dug and the __<b>95</b>__ were brought from somewhere else. __<b>96</b>__ was made from a mixture of sand, cement and water, and the walls grew before our very eyes. Before the end of the second month, we realized ot was not going to be a __<b>97</b>__ but a storeyed building. The __<b>98</b>__ was cast in only one day by the workers who __<b>99</b>__ for the whole day. Thereafter, things moved even faster. By the end of the month, the whole __<b>100</b>__ was in place.</font>","A. roofing","B. decking","C. floor","D. beam","","98/100"));	//98
		fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>PASSAGE B</b>\n\tIt is interesting to watch a modern __<b>88</b>__ spring up and get completed in a matter of months. A few months ago, a building company brought some __<b>89</b>__ to the virgin forest next to our school. The trees were __<b>90</b>__, the ground was cleared and __<b>91</b>__, and the workers brought out various __<b>92</b>__ with which they measured and marked the __<b>93</b>__. Then the _<b>94</b>__ was dug and the __<b>95</b>__ were brought from somewhere else. __<b>96</b>__ was made from a mixture of sand, cement and water, and the walls grew before our very eyes. Before the end of the second month, we realized ot was not going to be a __<b>97</b>__ but a storeyed building. The __<b>98</b>__ was cast in only one day by the workers who __<b>99</b>__ for the whole day. Thereafter, things moved even faster. By the end of the month, the whole __<b>100</b>__ was in place.</font>","A. struggled","B. grumbled","C. suffered","D. toiled","","99/100"));	//99
		fQuestions->push_back(QuestionAnswer("<font size=6>\t\t<b>PASSAGE B</b>\n\tIt is interesting to watch a modern __<b>88</b>__ spring up and get completed in a matter of months. A few months ago, a building company brought some __<b>89</b>__ to the virgin forest next to our school. The trees were __<b>90</b>__, the ground was cleared and __<b>91</b>__, and the workers brought out various __<b>92</b>__ with which they measured and marked the __<b>93</b>__. Then the _<b>94</b>__ was dug and the __<b>95</b>__ were brought from somewhere else. __<b>96</b>__ was made from a mixture of sand, cement and water, and the walls grew before our very eyes. Before the end of the second month, we realized ot was not going to be a __<b>97</b>__ but a storeyed building. The __<b>98</b>__ was cast in only one day by the workers who __<b>99</b>__ for the whole day. Thereafter, things moved even faster. By the end of the month, the whole __<b>100</b>__ was in place.</font>","A. roof","B. structure","C. wall","D. apartment","","100/100"));	//100
		

        fQuestions->push_back(QuestionAnswer(QPixmap::fromImage(QImage(":/images/JAMB/2008/English/1.png")),"A. sanguine","B. jiraiya","C. nagato","D. naruto","E. kakashi","extra(naruto fans)"));

        return;
    }

    void setupAnswers()
    {
        fAnswers->push_back(1);  fAnswers->push_back(4);  fAnswers->push_back(1);  fAnswers->push_back(3);  fAnswers->push_back(3);  fAnswers->push_back(3);  fAnswers->push_back(1);  fAnswers->push_back(2);  fAnswers->push_back(3);  fAnswers->push_back(1);
        fAnswers->push_back(4);  fAnswers->push_back(4);  fAnswers->push_back(2);  fAnswers->push_back(1);  fAnswers->push_back(2);  fAnswers->push_back(2);  fAnswers->push_back(2);  fAnswers->push_back(4);  fAnswers->push_back(2);  fAnswers->push_back(4);
        fAnswers->push_back(3);  fAnswers->push_back(3);  fAnswers->push_back(1);  fAnswers->push_back(4);  fAnswers->push_back(1);  fAnswers->push_back(2);  fAnswers->push_back(3);  fAnswers->push_back(3);  fAnswers->push_back(3);  fAnswers->push_back(2);
        fAnswers->push_back(1);  fAnswers->push_back(1);  fAnswers->push_back(2);  fAnswers->push_back(3);  fAnswers->push_back(3);  fAnswers->push_back(1);  fAnswers->push_back(1);  fAnswers->push_back(2);  fAnswers->push_back(3);  fAnswers->push_back(4);
        fAnswers->push_back(1);  fAnswers->push_back(2);  fAnswers->push_back(4);  fAnswers->push_back(4);  fAnswers->push_back(2);  fAnswers->push_back(1);  fAnswers->push_back(3);  fAnswers->push_back(1);  fAnswers->push_back(2);  fAnswers->push_back(2);
        fAnswers->push_back(3);  fAnswers->push_back(2);  fAnswers->push_back(4);  fAnswers->push_back(3);  fAnswers->push_back(2);  fAnswers->push_back(4);  fAnswers->push_back(2);  fAnswers->push_back(3);  fAnswers->push_back(4);  fAnswers->push_back(3);
        fAnswers->push_back(3);  fAnswers->push_back(2);  fAnswers->push_back(3);  fAnswers->push_back(3);  fAnswers->push_back(2);  fAnswers->push_back(1);  fAnswers->push_back(4);  fAnswers->push_back(2);  fAnswers->push_back(1);  fAnswers->push_back(4);
        fAnswers->push_back(2);  fAnswers->push_back(4);  fAnswers->push_back(2);  fAnswers->push_back(2);  fAnswers->push_back(0);  fAnswers->push_back(2);  fAnswers->push_back(1);  fAnswers->push_back(3);  fAnswers->push_back(2);  fAnswers->push_back(3);
        fAnswers->push_back(3);  fAnswers->push_back(3);  fAnswers->push_back(3);  fAnswers->push_back(4);  fAnswers->push_back(1);  fAnswers->push_back(3);  fAnswers->push_back(2);  fAnswers->push_back(2);  fAnswers->push_back(2);  fAnswers->push_back(1);
        fAnswers->push_back(1);  fAnswers->push_back(4);  fAnswers->push_back(3);  fAnswers->push_back(2);  fAnswers->push_back(4);  fAnswers->push_back(3);  fAnswers->push_back(3);  fAnswers->push_back(2);  fAnswers->push_back(4);  fAnswers->push_back(2);

        fAnswers->push_back(2);
    }

public:
    Jamb2008English():QuestionBank(1,"Jamb 2008, English")
    {
        setupQuestions();
        setupAnswers();
        fMax_Question=fQuestions->size();
    }
};


class Jamb2008Maths:public QuestionBank
{
    void setupQuestions()
    {
        return;
    }

    void setupAnswers()
    {
        return;
    }

public:
    Jamb2008Maths():QuestionBank(2,"Jamb 2008, Maths")
    {
        setupQuestions();
        setupAnswers();
        fMax_Question=fQuestions->size();
    }
};


class Jamb2009English:public QuestionBank
{
    void setupQuestions()
    {
        return;
    }

    void setupAnswers()
    {
        return;
    }

public:
    Jamb2009English():QuestionBank(2,"Jamb 2009, English")
    {
        setupQuestions();
        setupAnswers();
        fMax_Question=fQuestions->size();
    }
};



class Jamb2009Maths:public QuestionBank
{
    void setupQuestions()
    {
        return;
    }

    void setupAnswers()
    {
        return;
    }

public:
    Jamb2009Maths():QuestionBank(2,"Jamb 2009, Maths")
    {
        setupQuestions();
        setupAnswers();
        fMax_Question=fQuestions->size();
    }
};


#endif // BANK_H

